image: ghcr.io/foundry-rs/foundry:latest

definitions:
  caches:
    foundry: ~/.foundry
    forge-libs: lib

pipelines:
  default:
    - step:
        name: Build & Test
        caches:
          - foundry
          - forge-libs
        script:
          - forge install
          - forge build --sizes
          - forge test -vvv
          - forge snapshot
        artifacts:
          - .gas-snapshot

  pull-requests:
    '**':
      - step:
          name: Run tests
          caches:
            - foundry
            - forge-libs
          script:
            - forge install
            - forge build
            - forge test -vvv
            - forge snapshot
            - |
              if [ -f .gas-snapshot ]; then
                echo "Checking gas snapshot changes..."
              fi
